# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: birling 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "birling"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Scott Tadman"]
  s.date = "2015-01-31"
  s.description = "Mostly drop-in replacement for Logger with a more robust log rotation facility"
  s.email = "github@tadman.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "birling.gemspec",
    "lib/birling.rb",
    "lib/birling/formatter.rb",
    "lib/birling/logger.rb",
    "lib/birling/support.rb",
    "test/helper.rb",
    "test/test_birling.rb",
    "test/test_birling_logger.rb",
    "test/test_birling_support.rb"
  ]
  s.homepage = "http://github.com/twg/birling"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Logger with simple log rotation system"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

